### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Othman2001** [AndreasBurbach/react-image-design-editor#7]
i am trying to add this repo to my existing react 17 / webpack project 
i have faced some issues like export defualt errors but i fixed it in handlers however i still having this problem 
```
GuidelineHandler.ts:378 Uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization
    at Module.default (GuidelineHandler.ts:378:1)
    at Module.Handler (ZoomHandler.ts:152:1)
    at registerExportsForReactRefresh (RefreshUtils.js:147:1)
    at Object.executeRuntime (RefreshUtils.js:182:1)
    at $ReactRefreshModuleRuntime$ (index.ts:43:1)
    at Module../src/modules/editor/components/canvas/handlers/index.ts (index.ts:43:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/modules/editor/components/canvas/handlers/Handler.ts (GuidelineHandler.ts:378:1)
```

**Comment by Othman2001** [comment]
@AndreasBurbach i have created most important pull request please review it

**Comment by Othman2001** [comment]
@AndreasBurbach 
no in my pull request i have fixed this  error

**Comment by Othman2001** [comment]
@AndreasBurbach  i have found some issues on my pull request i will do my best to fix it tonight and then i will re open my pr

**Comment by AndreasBurbach** [comment]
okay 👍

**Comment by Othman2001** [comment]
@AndreasBurbach  
https://github.com/Othman2001/react-image-design-editor/tree/fixing-isssues

**Comment by AndreasBurbach** [comment]
i dont know what you mean with data-panel left. What i see is, that you not showing the default image by clicking on image, but adding an image to that object is working.

**Comment by Othman2001** [comment]
@AndreasBurbach  ohhh ! i am sorry for this mistake, i just got confused. but everything is working fine now , i have re opened the pull request i hope you review it and if there is any issue tell me to fix it. 
Thanks 😊
